service: sw-code-crawler
#app: your-app-name
#tenant: your-tenant-name
provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: eu-west-1
  memorySize: 128M

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "CodesTendancieuBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "cloudfront:CreateInvalidation"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "CodesTendancieuBucket"
            - "/*"

functions:
  crawl:
    handler: crawler.crawl
    events:
       - schedule: cron(*/15 * * * ? *)

#    Define function environment variables here
    environment:
      reddit_client_id: ${file(./config.json):reddit_client_id}
      reddit_client_secret: ${file(./config.json):reddit_client_secret}
      distribution_id: ${file(./config.json):distribution_id}
      bucket: "sw-codes-tendancieu-eu-west-1"

# you can add CloudFormation resource templates here
resources:
 Resources:
  CrawlLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: 
        RetentionInDays: 14
  CodesTendancieuBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sw-codes-tendancieu-eu-west-1
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-python-requirements
